/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enc_mods_test;

import enc_mods.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author YING LOPEZ
 */
public class test_module extends javax.swing.JFrame {

    /**
     * Creates new form test_module
     */
    
    private time_algo tester;
    private aes encmodorig;
    private text_aes encmodtext;
    private file_aes encmodfile;
    
    private File selfile;
    
    public test_module() {
        encmodorig = new aes();
        encmodtext = new text_aes(encmodorig);
        encmodfile = new file_aes(encmodorig);
        tester = null;
        selfile = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textfieldinput = new javax.swing.JTextField();
        textencbtn = new javax.swing.JButton();
        textdecbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        selectfilebtn = new javax.swing.JButton();
        textfieldfile = new javax.swing.JTextField();
        fileencbtn = new javax.swing.JButton();
        filedecbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textfieldoutput = new javax.swing.JTextField();
        texttime = new javax.swing.JLabel();
        filetime = new javax.swing.JLabel();
        hashtextbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Encryption/Decryption Module");
        title.setToolTipText("");

        jLabel1.setText("Enter text:");

        textencbtn.setText("AES Enc!");
        textencbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textencbtnActionPerformed(evt);
            }
        });

        textdecbtn.setText("AES Dec!");
        textdecbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdecbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Selected file:");

        selectfilebtn.setText("Select File");
        selectfilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectfilebtnActionPerformed(evt);
            }
        });

        textfieldfile.setEditable(false);
        textfieldfile.setText("Click adjacent button to select a file ->");

        fileencbtn.setText("AES Enc!");
        fileencbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileencbtnActionPerformed(evt);
            }
        });

        filedecbtn.setText("AES Dec!");
        filedecbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedecbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Text output:");

        textfieldoutput.setEditable(false);

        hashtextbtn.setText("Hash!");
        hashtextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashtextbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(filetime))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textfieldfile, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selectfilebtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(textfieldinput, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                                .addGap(67, 67, 67))
                                            .addComponent(textfieldoutput))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hashtextbtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(title)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(texttime))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fileencbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(filedecbtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textencbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textdecbtn)))))
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textfieldinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textencbtn)
                    .addComponent(textdecbtn)
                    .addComponent(hashtextbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textfieldoutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texttime))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textfieldfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectfilebtn)
                    .addComponent(fileencbtn)
                    .addComponent(filedecbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filetime)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hashtextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashtextbtnActionPerformed
        // TODO add your handling code here:
        if(textfieldinput.getText()==""){
            JOptionPane.showMessageDialog(this, "Please enter text as input.");
        } else {
            tester = new time_algo(encmodtext);
            try{
            FileWriter fw = new FileWriter("test_log.txt", true);
            tester.setFileLog(fw);
            textfieldoutput.setText(encmodtext.getHashedString(textfieldinput.getText()));
            tester.writeEncTime(22, null, textfieldinput.getText());
            tester.finishTest();
            tester = null;
            } catch (Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_hashtextbtnActionPerformed

    private void textencbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textencbtnActionPerformed
        // TODO add your handling code here:
        if(textfieldinput.getText()==""){
            JOptionPane.showMessageDialog(this, "Please enter text as input.");
        } else {
            tester = new time_algo(encmodtext);
            try{
            FileWriter fw = new FileWriter("test_log.txt", true);
            tester.setFileLog(fw);
            textfieldoutput.setText(encmodtext.getEncString(textfieldinput.getText()));
            tester.writeEncTime(21, null, textfieldinput.getText());
            tester.finishTest();
            tester = null;
            } catch (Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_textencbtnActionPerformed

    private void textdecbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdecbtnActionPerformed
        // TODO add your handling code here:
        if(textfieldinput.getText()==""){
            JOptionPane.showMessageDialog(this, "Please enter text as input.");
        } else {
            tester = new time_algo(encmodtext);
            try{
            FileWriter fw = new FileWriter("test_log.txt", true);
            tester.setFileLog(fw);
            textfieldoutput.setText(encmodtext.getDecString(textfieldinput.getText()));
            tester.writeDecTime(2, null, textfieldinput.getText());
            tester.finishTest();
            tester = null;
            } catch (Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_textdecbtnActionPerformed

    private void selectfilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectfilebtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int rVal = fileChooser.showOpenDialog(null);
        if (rVal == JFileChooser.APPROVE_OPTION){
            selfile = fileChooser.getSelectedFile();
            textfieldfile.setText(selfile.getName());
        }
    }//GEN-LAST:event_selectfilebtnActionPerformed

    private void fileencbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileencbtnActionPerformed
        // TODO add your handling code here:
        if(selfile==null){
            JOptionPane.showMessageDialog(this, "Please select a file as input.");
        } else {
            tester = new time_algo(encmodfile);
            try{
            FileWriter fw = new FileWriter("test_log.txt", true);
            tester.setFileLog(fw);
            tester.writeEncTime(3, selfile, null);
            tester.finishTest();
            tester = null;
            selfile = null;
            } catch (Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_fileencbtnActionPerformed

    private void filedecbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedecbtnActionPerformed
        // TODO add your handling code here:
        if(selfile==null){
            JOptionPane.showMessageDialog(this, "Please select a file as input.");
        } else {
            tester = new time_algo(encmodfile);
            try{
            FileWriter fw = new FileWriter("test_log.txt", true);
            tester.setFileLog(fw);
            tester.writeDecTime(3, selfile, null);
            tester.finishTest();
            tester = null;
            selfile = null;
            } catch (Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_filedecbtnActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(test_module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(test_module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(test_module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(test_module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new test_module().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filedecbtn;
    private javax.swing.JButton fileencbtn;
    private javax.swing.JLabel filetime;
    private javax.swing.JButton hashtextbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton selectfilebtn;
    private javax.swing.JButton textdecbtn;
    private javax.swing.JButton textencbtn;
    private javax.swing.JTextField textfieldfile;
    private javax.swing.JTextField textfieldinput;
    private javax.swing.JTextField textfieldoutput;
    private javax.swing.JLabel texttime;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
